### ISSUE TITLE
Exporting NatsError

### ISSUE THREAD

**Issue by leolanavo** [nats-io/ts-nats#32]
Hi everyone,

It would be very awesome, if you exported the `NatsError` type, so you can properly type the `MsgCallbacks`.

This:
```
import { Msg } from 'ts-nats';

nats.subscribe('foo', (err: any, msg: Msg) => console.log(msg.subject);
```

Could become this:
```
import { Msg, NatsError } from 'ts-nats';

nats.subscribe('foo', (err: NatsError | null, msg: Msg) => console.log(msg.subject);
```

Way more beatiful, when you can type everything, and the code become more human friendly.

**Comment by aricart** [comment]
Looking into this - the main issue is the packaging dependencies.
TS-nats is currently architected so that additional transports will plug into it. So some dependencies cannot leak through.

For now you can try 

`import {NatsError} from "ts-nats/lib/error";`

If you have any suggestions let me know.

**Comment by aricart** [comment]
@leolanavo actually the solution is trivial - ts-nats just needs a simple export of the types that it imported and it does it. Putting a fix in.
